project:
  type: website

website:
  title: "Note de recherche"

format:
  html:
    css: styles.css
    lang: fr
    toc: true
    toc-depth: 3
    number-sections: true
    anchor-sections: true
    html-math-method: mathjax
    theme: cosmo
    code-fold: true
